[package]
name = "rmcs-actions-service"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.100"
chrono = { version = "0.4", features = ["serde"] }
dashmap = "6.1.0"
dotenvy = "0.15.7"
futures-util = "0.3.31"
log = "0.4.29"
log4rs = "1.4.0"
poem = { version = "3.1.12", features = ["server", "compression", "cookie", "rustls", "sse", "anyhow", "yaml", "sonic-rs", "websocket"] }
poem-openapi = { version = "5.1.16", features = ["chrono", "swagger-ui", "uuid", "sonic-rs"] }
sealed = "0.6.0"
serde = { version = "1.0.228", features = ["derive", "serde_derive"] }
serde_json = "1.0.116"
serde_with = "3.16.1"
sonic-rs = "0.5.6"
tokio = { version = "1.48.0", features = ["time", "fs", "rt-multi-thread", "parking_lot"] }
uuid = { version = "1.19.0", features = ["v4"] }
