[project]
name = "rmcs-actions-client"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [{ name = "Embers-of-the-Fire", email = "stellarishs@163.com" }]
requires-python = ">=3.13"
dependencies = [
    "aiohttp>=3.13.2",
    "psutil>=7.1.3",
    "pydantic>=2.12.5",
    "python-dotenv>=1.2.1",
    "pyyaml>=6.0.3",
    "schedule>=1.2.2",
    "websockets>=15.0.1",
]

[project.scripts]
daemon = "rmcs_actions_client:main"

[build-system]
requires = ["uv_build>=0.9.12,<0.10.0"]
build-backend = "uv_build"

[dependency-groups]
dev = ["devtools>=0.12.2", "pytest>=9.0.1", "ruff>=0.14.7"]
