[project]
name = "bot"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Embers-of-the-Fire", email = "stellarishs@163.com" }
]
requires-python = ">=3.13"
dependencies = [
    "psutil>=7.1.3",
    "pydantic>=2.12.5",
]

[project.scripts]
bot = "bot:main"

[build-system]
requires = ["uv_build>=0.9.12,<0.10.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "devtools>=0.12.2",
    "pytest>=9.0.1",
    "ruff>=0.14.7",
]
